### ISSUE TITLE
performance Issue on keras.

### ISSUE THREAD

**Issue by talregev** [pyamsoft/pydroid#19]
I install keras with theano on pydroid 3 and run simple algorithm on mnist.    
It run so slow that one epoch take more than a day.

then I install Ubuntu on my phone. the same phone before. install keras with theano and run the same mnist algorithm, it take 1min for epoch. big difference.
I download libopenblas with apt install, also liblapack and gfortran that pip install scipy with openblas.

The libraries numpy scipy and also theano are link to openblas, and my guess yours libraries are not.
Can you create numpy, scipy and theano linked to openblas. that it can be easy install (for me it take one day to setup all the stuff) and faster with performance that many people can run deep learning on the phone.

**Comment by pyamsoft** [comment]
Hi

I think there is a misunderstanding here. PYDroid is not a deep learning
library, nor does it seek to be. Attempting to compare it to something like
Keras is pointless.

You may be looking for the Pydroid 3 IDE, which is a different project
