### ISSUE TITLE
Ai assistant 

### ISSUE THREAD

**Issue by Xzibitphanbeez** [pyamsoft/pydroid#443]
How do I create an ai assistant using pydroid

**Comment by pyamsoft** [comment]
Hi, this is the wrong repository. You are probably looking for the pydroid IDE, not this library :)

**Comment by Xzibitphanbeez** [comment]
Ok, but please can you guide me through how to I can use the correct
repository for pydroid?

**Comment by pyamsoft** [comment]
Hi, I've never used it before, but I think you are looking for this instead

https://play.google.com/store/apps/details?id=ru.iiec.pydroid3&hl=en-US

Cheers
